<?php
declare(strict_types=1);

/** @var \Movistar\HyvaWidgets\Block\Organism\BenefitsCards $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

use Movistar\HyvaWidgets\ViewModel\TemplateRenderer;

$benefits = $block->getBenefits();
$templateRenderer = $viewModels->require(TemplateRenderer::class);
?>

<!-- Benefits -->
<div class="mx-auto min-w-[328px] w-full grid grid-cols-1 gap-4 px-4 mt-6 mb-7.5 md:mb-[72px] md:px-0 md:max-w-[464px]
            lg:mt-20 lg:mb-28 lg:max-w-[784px] lg:px-0 lg:grid-cols-2 lg:gap-6 xl:max-w-[856px] xl:mb-12">
    <?php foreach ($benefits as $benefit): ?>
        <?php
        if (empty($benefit['content'])) {
            continue;
        }
        ?>
        <?= /* @noEscape */ $templateRenderer->render(
            'Magento_Theme::molecule/benefit_card.phtml',
            [
                'benefit_card_title'   => $benefit['title'],
                'benefit_card_content' => $benefit['content'],
                'benefit_card_image'   => $benefit['image'],
                'benefit_mobile_image' => $benefit['mbimage'],
            ],
            \Movistar\HyvaWidgets\Block\Molecule\BenefitCard::class
        ) ?>
    <?php endforeach; ?>
</div>
