<?php
/** @var \Movistar\HyvaWidgets\Block\Molecule\BenefitCard $block */
/** @var \Magento\Framework\Escaper $escaper */

$title = $block->getData('benefit_card_title');
$content = $block->getDecodedContent('benefit_card_content');
$image = $block->resolveImage($block->getData('benefit_card_image'));
$mobileImageUrl = $block->resolveImage($block->getData('benefit_mobile_image'));

?>

<!-- Benefits Card -->
<div class="flex flex-col bg-white rounded-lg border border-neutral-200 w-full h-auto
            lg:w-[384px] lg:max-h-[272px] xl:w-[416px]">
    <div class="flex md:flex-row">
        <div class="flex-1 px-4 py-6 md:px-6 md:py-8 lg:pl-6 lg:pr-2 lg:py-8">
            <h3 class="font-roboto text-text-primary mb-2 text-lg leading-6 lg:text-xl lg:leading-7">
                <?= $escaper->escapeHtml($title) ?>
            </h3>
            <p class="font-roboto font-normal text-text-gray m-0 text-sm leading-5 lg:text-base lg:leading-6">
                <?= $escaper->escapeHtml($content) ?>
            </p>
        </div>
        <?php if ($image): ?>
                <picture>
                    <source
                        media="(min-width: 1024px)"
                        srcset="<?= /* @noEscape */ $image ?>"
                    />
                    <img
                        src="<?= /* @noEscape */ $mobileImageUrl ?>"
                        alt="<?= $escaper->escapeHtmlAttr($title) ?>"
                        class="w-[100px] h-full rounded-r-lg object-cover md:max-h-full lg:max-h-[272px]"
                        loading="lazy"
                    />
                </picture>
        <?php endif; ?>
    </div>
</div>
