<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Movistar\HyvaWidgets\Block\Molecule\ProductCard;
use Hyva\Theme\ViewModel\HyvaCsp;
use Movistar\HyvaWidgets\ViewModel\TemplateRenderer;
use Movistar\HyvaWidgets\Block\Atom\InfoCard;

/** @var ProductCard $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

$productData = $block->getPreparedProductData();
$withoutTax = $productData['without_tax'];

$templateRenderer = $viewModels->require(TemplateRenderer::class);

$sku = $productData['no_totalizable']['sku'] ?? '';

?>

<div class="min-w-full flex-shrink-0 box-border mx-auto"
     data-role="card-item"
     data-product-id="<?= $escaper->escapeHtmlAttr($productData['productId']) ?>"
     data-element-ga="product"
     data-ga-business-team="hogar"
     data-ga-business-mod="b2c"
     data-ga-product-comercial_name="
     <?= $escaper->escapeHtmlAttr($productData['title'][0] .' '. $productData['title'][1]) ?>"
     data-ga-product-comercial_id="<?= $escaper->escapeHtmlAttr($productData['sku']) ?>"
>
    <div class="rounded-2xl w-full bg-white h-full mx-auto min-w-[296px] max-w-[296px] flex flex-col justify-start
        min-h[452px] max-h-[562px] md:min-w-[254px] md:max-w-[254px] lg:min-w-[288px] lg:max-w-[288px]
        <?= $productData['is_featured_card'] == __('yes') ? ' border-2 border-(--color-primary)' :
        'border border-neutral-200 mt-6 mb-8' ?>"
    >

        <!-- Badge -->
        <?php if ($productData['is_featured_card'] == __('yes')): ?>
            <span class="flex justify-center items-center gap-1 bg-(--color-primary) text-white
                text-sm font-medium leading-5 px-3 py-1 rounded-t-[14px] relative font-roboto">
                <img
                    src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/icons/icon-light.svg')) ?>"
                    alt="icon-light"
                    class="w-4 h-4"
                />
                <?= $escaper->escapeHtml($productData['text_featured_card']) ?>
            </span>
        <?php endif; ?>

        <!-- Title -->
        <?php $roundedClass = ($productData['is_featured_card'] == __('yes')) ? '' : 'rounded-t-2xl'; ?>
        <div class="bg-third pt-4 pb-6 text-on-primary text-center font-roboto relative mb-5 lg:pb-8 lg:mb-5.5
            <?= $escaper->escapeHtml($roundedClass) ?>">
            <p class="text-sm leading-5 font-normal mb-1 lg:text-base lg:leading-6 lg:m-0">
                <?= $escaper->escapeHtml(__('Movistar Fibra')) ?>
            </p>
            <h3 class="text-[28px] leading-8 lg:text-[32px] lg:leading-10">
                <?php if ($productData['sku'] == 'internet_service_tota_2GIGASf'): ?>
                    <?= $escaper->escapeHtml(__('Hyperspeed')) ?>
                <?php elseif (!empty($productData['megas'])): ?>
                    <?= $escaper->escapeHtml(is_array($productData['megas'])
                        ? implode(' ', $productData['megas'])
                        : $productData['megas']) ?>
                <?php endif; ?>
            </h3>

            <!-- Offer -->
            <?php if (!empty($productData['card_promo_info'])): ?>
                <?= /* @noEscape */ $templateRenderer->render(
                    'Magento_Theme::atoms/label.phtml',
                    [
                        'label' => $productData['card_promo_info'],
                        'color' => '#E63780',
                        'image' => 'icon-gift'
                    ]
                ) ?>
            <?php endif; ?>
        </div>

        <!-- Price -->
        <div class="text-text-gray font-roboto text-center mb-4">
            <p class="text-xs leading-4 mb-0 lg:text-sm lg:leading-5">
                <?= $escaper->escapeHtml(__("If you have a Movistar cell phone")) ?>
            </p>
            <p class="font-telefonicaweb text-[28px] leading-8 text-text-primary m-0 lg:text-[32px] lg:leading-10">
                <?= $escaper->escapeHtml($productData['price'] ?? '') ?>
                <span class="font-roboto text-base leading-6 ml-1 lg:text-[22px] lg:leading-6 lg:font-telefonicaweb">
                    <?= $escaper->escapeHtml(__('per month')) ?>
                </span>
            </p>
            <?php if (!empty($productData['old_price'])): ?>
                <p class="text-xs leading-4  mb-0 lg:text-sm lg:leading-5">
                    <?= $escaper->escapeHtml(__('Before')) ?>
                    <span class="line-through"><?= $escaper->escapeHtml($productData['old_price']) ?></span>
                </p>
                <?php if ($productData['sku'] == 'internet_service_tota_2GIGASf'): ?>
                    <p class="text-sm mb-0"><?= $escaper->escapeHtml($productData['2_gigas_text']) ?></p>
                <?php endif; ?>
            <?php endif; ?>
        </div>

        <!-- Benefits -->
        <?php
        $benefit = $escaper->escapeHtml(__('If you dont have a Movistar phone, you pay')) . ' '
            . ($productData['no_totalizable']['price'] ?? '') . ' '
            . $escaper->escapeHtml(__('per month'));
        ?>

        <?= /* @noEscape */ $templateRenderer->render(
            'Magento_Theme::atoms/info_card.phtml',
            [
                'style' => 's1',
                'text' => $benefit
            ]
        ) ?>

        <?php if ($productData['megas'] >= 600): ?>
            <?= /* @noEscape */ $templateRenderer->render(
                'Magento_Theme::atoms/info_card.phtml',
                [
                    'style' => 's2',
                    'text' => $productData['info_text'],
                    'tooltip' => $productData['info_tooltip']
                ],
                InfoCard::class
            ) ?>
        <?php endif; ?>

        <!-- CTA -->
        <?php if ($productData['internal_url']): ?>
            <form
                x-data="initCreateCartForm({sku: '<?= $escaper->escapeHtmlAttr($sku) ?>'})"
                x-ref="form"
                method="post"
                class="form check-availability-form"
            >

                <input type="hidden" name="internetId" :value="sku">
                <div class="block w-full max-w-full text-center mx-auto box-border">
                    <button
                        type="button"
                        @click="sendToCreateCart"
                        class="relative text-center font-roboto font-medium bg-primary text-on-primary
                           text-base leading-6 px-4 py-3 rounded-full inline-block w-full max-w-[264px] box-border
                           md:max-w-[222px] lg:max-w-[256px] lg:text-lg lg:leading-6"
                    >
                    <span>
                        <?= $escaper->escapeHtml(__($productData['label_button_card'])) ?>
                    </span>
                    </button>
                </div>
            </form>
        <?php else: ?>
            <div x-data="initLinkWithLoader()" class="block w-full text-center">
                <a
                    @click="handleClick"
                    href="/<?= $escaper->escapeHtml($productData['button_card_link']) ?>"
                    class="relative text-center font-roboto font-medium bg-primary text-on-primary
                    text-base leading-6 p-3 rounded-full inline-block min-w-[256px]"
                    title="<?= $escaper->escapeHtmlAttr($productData['label_button_card']) ?>"
                >
                    <?= $escaper->escapeHtml($productData['label_button_card']) ?>
                </a>
            </div>
        <?php endif; ?>

        <!-- Footnote -->
        <div class="text-text-gray font-roboto text-center text-xs leading-4 mt-10 mb-6 lg:text-sm lg:leading-5">
            <p class="m-0">
                <?= $escaper->escapeHtml(__('Prices without national taxes:')) ?>
            </p>
            <p class="m-0">
                <?= $escaper->escapeHtml(__("with Movistar cell phone")) ?>
                <?= $escaper->escapeHtml(
                    $withoutTax->generatePriceWithoutTax(
                        (float)(
                        !empty($productData['special_price_without_currency'])
                            ? $productData['special_price_without_currency']
                            : $productData['price_without_currency']
                        )
                    )
                ) ?>
            </p>

            <p class="m-0">
                <?= $escaper->escapeHtml(__("without a Movistar cell phone")) ?>
                <?= $escaper->escapeHtml(
                    $withoutTax->generatePriceWithoutTax(
                        (float)(
                            $productData['no_totalizable']['special_price_without_currency']
                            ?? $productData['no_totalizable']['price_without_currency']
                            ?? $productData['price_without_currency']
                        )
                    )
                ) ?>
            </p>
        </div>
    </div>
</div>
